@startuml
start

:Add donor-recipient pairs;
:Store data in database;
:Run compatibility engine algorithm;

if () then ([Matches Found])
  :Display possible swaps;
  if () then ([Approved])
    :Update records;
  else ([Not Approved])
    :Reject match;
  endif
else ([No Match Found])
endif

stop
@enduml
